services:
  bifrost:
    image: kartoffelchipss/bifrost:latest
    container_name: bifrost
    restart: unless-stopped
    env_file:
      - .env
    environment:
      BF_FLUXER_DOMAIN: ${BF_FLUXER_DOMAIN:-fluxer.app}
      BF_FLUXER_API_BASE: ${BF_FLUXER_API_BASE:-}
      BF_FLUXER_WEB_BASE: ${BF_FLUXER_WEB_BASE:-}
    volumes:
      - ./config:/config