services:
    bifrost:
        image: ghcr.io/4g0tt3nsou1/bifrost:latest
        container_name: bifrost
        restart: unless-stopped
        environment:
            BF_DB_DIALECT: sqlite
            BF_FLUXER_TOKEN_FILE: /root/.creds/bf_flux
            BF_DISCORD_TOKEN_FILE: /root/.creds/bf_discord
            BF_FLUXER_APP_ID: 1478333491047665698
            BF_DISCORD_APP_ID: 1478331623853260892
            BF_FLUXER_OWNER_ID: 1475309609460187238
            BF_DISCORD_OWNER_ID: 391124319444533249
            BF_COMMAND_PREFIX: "%"
            BF_CONFIG_PATH: /config
            BF_DISCORD_HEALTH_URL: https://status.sou1.dev/api/push
            BF_DISCORD_HEALTH_TOKEN_FILE: /root/.creds/bf_hc_discord
            BF_FLUXER_HEALTH_URL: https://status.sou1.dev/api/push
            BF_FLUXER_HEALTH_TOKEN_FILE: /root/.creds/bf_hc_flux
            NODE_ENV: development
            BF_METRICS_PORT: "9091"
            BF_DELETE_INVOCATION: "true"
        volumes:
            - bifrost:/config
            - /root/.creds/bf_flux:/root/.creds/bf_flux:ro
            - /root/.creds/bf_discord:/root/.creds/bf_discord:ro
            - /root/.creds/bf_hc_discord:/root/.creds/bf_hc_discord:ro
            - /root/.creds/bf_hc_flux:/root/.creds/bf_hc_flux:ro
        networks:
            - bifrost
            - npm

volumes:
    bifrost:

networks:
    bifrost:
        driver: bridge
    npm:
        external: true
        name: npm_default
